variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - module-pipelines
  - kubernetes-pipelines

frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend
  # only:
  #   changes:
  #     - frontend/**/*

backend:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend
  # only:
  #   changes:
  #     - backend/**/*

backend_report:
  stage: module-pipelines
  trigger:
    include:
      - "/backend-report/.gitlab-ci.yml"
    strategy: depend
  # only:
  #   changes:
  #     - backend-report/**/*


kubernetes:
  stage: kubernetes-pipelines
  trigger:
    include:
      - "/kubernetes/.gitlab-ci.yml"
    strategy: depend
  # only:
  #   changes:
  #     - kubernetes/**/*
