variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - module-pipelines

kubernetes:
  stage: module-pipelines
  trigger:
    include:
      - "/kubernetes/.gitlab-ci.yml"
    strategy: depend
  # only:
  #   changes:
  #     - kubernetes/**/*
