variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - module-pipelines

helm-kubernetes:
  stage: module-pipelines
  trigger:
    include:
      - "/sausage-store-chart/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - sausage-store-chart/**/*

