# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build
- test
- release
include:
- template: Security/SAST.gitlab-ci.yml
build-code-job:
  stage: build
  script:
  - echo "ARTIFACT_JOB_ID=${CI_JOB_ID}" > CI_JOB_ID.txt
  - cd backend
  - mvn package -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
  - cd ../frontend
  - npm install
  - npm run build
  - cd ..
  - mkdir sausage-store-0.0.1
  - cp backend/target/sausage-store-0.0.1-SNAPSHOT.jar backend/sausage-store-0.0.1.jar
  - mv backend/target/sausage-store-0.0.1-SNAPSHOT.jar sausage-store-0.0.1/sausage-store-0.0.1.jar
  - mv frontend/dist/frontend sausage-store-0.0.1/public_html
  artifacts:
    paths:
    - sausage-store-0.0.1/public_html
    - sausage-store-0.0.1/sausage-store-0.0.1.jar
    - backend/sausage-store-0.0.1.jar
    reports:
      dotenv: CI_JOB_ID.txt
spotbugs-sast:
  stage: test
  variables:
    COMPILE: 'false'
    MAVEN_REPO_PATH: "${CI_PROJECT_DIR}/backend/repository"
  artifacts:
    paths:
    - "${CI_PROJECT_DIR}/backend/"
upload-release:
  stage: release
  script:
  - echo "Get artifact from job ${ARTIFACT_JOB_ID}"
  - 'curl --location --output sausage-store-0.0.1.zip -H "PRIVATE-TOKEN: ${MY_TOKEN}"
    "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/jobs/${ARTIFACT_JOB_ID}/artifacts"

'
  - 'curl -sSL -H "JOB-TOKEN: ${CI_JOB_TOKEN}" -T sausage-store-0.0.1.zip "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/sausage-store/${CI_COMMIT_SHA}/"

'
sast:
  stage: test
