version: "3.3"
services:
  backend:
    image: gitlab.praktikum-services.ru:5050/rybalka-dmitrii/sausage-store/sausage-backend:latest
    # container_name: sausage-backend
    restart: unless-stopped
    environment:
      SPRING_FLYWAY_BASELINE: "false"
      SPRING_CLOUD_VAULT_HOST: ${VAULT_HOST}
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
      REPORT_PATH: ${REPORT_PATH}
    networks:
      - sausage-store
  report:
    image: gitlab.praktikum-services.ru:5050/rybalka-dmitrii/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    restart: unless-stopped
    environment:
      SPRING_FLYWAY_BASELINE: "false"
      SPRING_CLOUD_VAULT_HOST: ${VAULT_HOST}
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
    networks:
      - sausage-store
  frontend:
    image: gitlab.praktikum-services.ru:5050/rybalka-dmitrii/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: "web"
    networks:
      - sausage-store
networks:
  sausage-store:
