#!/bin/bash
set +e
cat > .env <<EOF
VAULT_HOST=${VAULT_HOST}
VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
SPRING_CLOUD_VAULT_TOKEN=${VAULT_TOKEN}
SPRING_CLOUD_VAULT_HOST=${VAULT_HOST}
REPORT_PATH=${REPORT_PATH}
LOG_PATH=${REPORT_PATH}
EOF

docker login -u $CI_REGISTRY_LOGIN -p $CI_REGISTRY_PASSWORD_MANUAL $CI_REGISTRY_URL

#set -e
docker-compose down || true
docker-compose up -d
