version: "3.4"
services:
  sausage-backend-blue:
    image: ${BACKEND_IMAGE_URL}
    container_name: sausage-backend-blue
    restart: unless-stopped
    environment:
      SPRING_FLYWAY_BASELINE: "false"
      SPRING_CLOUD_VAULT_HOST: ${VAULT_HOST}
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
      VIRTUAL_HOST: "web"
    networks:
      - sausage-store
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 15
  sausage-backend-green:
    image: ${BACKEND_IMAGE_URL}
    container_name: sausage-backend-green
    restart: unless-stopped
    environment:
      SPRING_FLYWAY_BASELINE: "false"
      SPRING_CLOUD_VAULT_HOST: ${VAULT_HOST}
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
      VIRTUAL_HOST: "web"
    networks:
      - sausage-store
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 15
  report:
    image: ${BACKEND_REPORT_IMAGE_URL}
    container_name: sausage-backend-report
    restart: unless-stopped
    environment:
      SPRING_FLYWAY_BASELINE: "false"
      SPRING_CLOUD_VAULT_HOST: ${VAULT_HOST}
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
    networks:
      - sausage-store
  frontend:
    image: ${FRONTEND_IMAGE_URL}
    container_name: sausage-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: "web"
    networks:
      - sausage-store
networks:
  sausage-store:
