#!/bin/bash
set +e
cat > .env <<EOF
REPORT_PATH=${REPORT_PATH}
LOG_PATH=${LOG_PATH}
SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
SPRING_CLOUD_VAULT_HOST=${VAULT_HOST}
SPRING_CLOUD_VAULT_TOKEN=${VAULT_TOKEN}
EOF
docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_CI
# set -e

docker-compose down || true
docker-compose up -d
