variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - deploy
deploy-kubernetes-helm:
  stage: deploy
  image: alpine/helm
  before_script:
    - apk add curl
    - mkdir -p .kube
    - echo ${CONFIG} | base64 -d > .kube/config
    - chmod go-r .kube/config
    - cat .kube/config
    - helm version
    - helm repo add sausage-store-chart ${NEXUS_REPO_URL_HELM} --username ${NEXUS_REPO_USER} --password ${NEXUS_REPO_PASS}
  script:
    - helm package ./sausage-store-chart --version ${VERSION}
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} ${NEXUS_REPO_URL_HELM} --upload-file ./sausage-store-${VERSION}.tgz
    - helm repo update sausage-store-chart
    - helm upgrade --install sausage-store sausage-store-chart/sausage-store --set environment=test --atomic --timeout 15m --kubeconfig .kube/config
