variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - build
  - deploy
  - release
deploy-kubernetes-helm:
  stage: build
  image: alpine/helm
  script:
    - helm package ./sausage-store-chart --version ${VERSION}
  artifacts:
    paths:
      - ./sausage-store-${VERSION}.tgz
    expire_in: 1 week

save-in-repo-kubernetes-helm:
  stage: deploy
  image: alpine/helm
  before_script:
    - apk add curl
  script:
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} ${NEXUS_REPO_URL_HELM} --upload-file ./sausage-store-${VERSION}.tgz

run-on-kuber:
  stage: release
  image: alpine/helm
  before_script:
    - apk add curl
    - export ARGOCD_SERVER=${ARGOCD_SERVER}
    - export ARGOCD_AUTH_TOKEN=${ARGO_TOKEN}
    - echo $ARGO_TOKEN
    - echo $ARGOCD_AUTH_TOKEN
    - echo $ARGOCD_SERVER
  script:
    - curl -sSL -o /usr/local/bin/argocd https://${ARGOCD_SERVER}/download/argocd-linux-amd64
    - chmod +x /usr/local/bin/argocd
    - argocd app sync sausage-store-dmitriy-rybalka --grpc-web
    - argocd app wait sausage-store-dmitriy-rybalka
