apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/rybalka-dmitrii/sausage-store/sausage-backend-report:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_FLYWAY_BASELINE-ON-MIGRATE
              value: "false"
            - name: SPRING_CLOUD_VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_host
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_token
            - name: REPORT_PATH
              value: /tmp
            - name: LOG_PATH
              value: /tmp
          ports:
            - name: backend
              containerPort: 8080
      imagePullSecrets:
        - name: docker-config-secret
