apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7ImF1dGgiOiJjbmxpWVd4cllTMWtiV2wwY21scFFIbGhibVJsZUM1eWRUbzBRek5OVkd0eWRUaDNlRWN0ZWpoQmVpMDFOUT09In19fQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
type: Opaque
data:
  vault_host: MTc4LjE1NC4yMDMuNDA=
  vault_token: SGZYblR4YTc1Wg==
