apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJnaXRsYWIrZGVwbG95LXRva2VuLTE3IiwicGFzc3dvcmQiOiJpazdUUEh6amF4RHE2VmJpQVNzZiIsImF1dGgiOiJaMmwwYkdGaUsyUmxjR3h2ZVMxMGIydGxiaTB4TnpwcGF6ZFVVRWg2YW1GNFJIRTJWbUpwUVZOelpnPT0ifX19
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
type: Opaque
data:
  vault_host: MTc4LjE1NC4yMDMuNDA=
  vault_token: SGZYblR4YTc1Wg==
