apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmlNVEF4TWpBeFFIbGhibVJsZUM1eWRUbzBhR0pHWkVnNFVFdE0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
type: Opaque
data:
  vault_host: MTc4LjE1NC4yMDMuNDA=
  vault_token: SGZYblR4YTc1Wg==
