variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - deploy
include:
  - project: "templates/ci"
    file: "DockerInDockerTemplate.yml"
deploy-kubernetes:
  stage: deploy
  # image: alpine:3.15.0
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 600 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - ssh ${DEV_USER}@${DEV_HOST} "mkdir -p ./task9-3"
    - ssh ${DEV_USER}@${DEV_HOST} "rm -rf ./task9-3/*"
    - scp -rp ./kubernetes/backend ${DEV_USER}@${DEV_HOST}:/home/student/task9-3
    - scp -rp ./kubernetes/backend-report ${DEV_USER}@${DEV_HOST}:/home/student/task9-3
    - scp -rp ./kubernetes/frontend ${DEV_USER}@${DEV_HOST}:/home/student/task9-3
    - ssh ${DEV_USER}@${DEV_HOST} "export "KUBECONF='${CONFIG}'";
      /bin/bash -s " < ./kubernetes/deploy-kubernetes.sh
  environment:
    name: rybalka-dmitrii-01.k8s.praktikum-services.tech
    url: https://rybalka-dmitrii-01.k8s.praktikum-services.tech
